# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  python.version: '2.7, 3.5, 3.6, >= 3.7.0a'
steps:
- task: UsePythonVersion@0
  displayName: 'Use Python $(python.version)'
  inputs:
    versionSpec: '$(python.version)'

steps:
- script: 'python -m pip install --upgrade pip && pip install -r requirements.txt' 
  displayName: 'Install dependencies'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    python manage.py test
  displayName: 'Run a multi-line script'

